document.addEventListener('DOMContentLoaded', () => {
    const chartTypeSelector = document.getElementById('chartTypeSelector');
    const countrySelector = document.getElementById('countrySelector');
    const imageContainer = document.getElementById('imageContainer');

    // 데이터 매핑
    const chartData = {
        gdp: ["Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda",
        "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain",
        "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan",
        "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria",
        "Burkina Faso", "Burundi", "Cambodia", "Cameroon", "Canada", "Central African Republic",
        "Chad", "Chile", "China", "Colombia", "Comoros", "Congo, Dem. Rep.",
        "Republic of the Congo", "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czech Republic",
        "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt",
        "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Swaziland", "Ethiopia",
        "Fiji", "Finland", "France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana",
        "Greece", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Honduras",
        "Hong Kong SAR, China", "Hungary", "Iceland", "India", "Indonesia",
        "Iran, Islamic Rep.", "Iraq", "Ireland", "Israel", "Italy", "Côte d'Ivoire",
        "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "South Korea",
        "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya",
        "Liechtenstein", "Lithuania", "Luxembourg", "Macao SAR, China", "Madagascar", "Malawi",
        "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania",
        "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro",
        "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Netherlands",
        "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Macedonia", "Norway", "Oman",
        "Pakistan", "Palau", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines",
        "Poland", "Portugal", "Qatar", "Romania", "Russian Federation", "Rwanda", "Samoa",
        "San Marino", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone",
        "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa",
        "South Sudan", "Spain", "Sri Lanka", "St. Kitts and Nevis", "St. Lucia",
        "St. Vincent and the Grenadines", "Sudan", "Suriname", "Sweden", "Switzerland",
        "Syrian Arab Republic", "Tajikistan", "Tanzania", "Thailand", "East Timor", "Togo",
        "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu",
        "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "Uruguay", "Uzbekistan",
        "Vanuatu", "Venezuela, RB", "Vietnam", "Yemen, Rep.", "Zambia", "Zimbabwe"],
        governance: ["Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda",
        "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain",
        "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan",
        "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria",
        "Burkina Faso", "Burundi", "Cambodia", "Cameroon", "Canada", "Central African Republic",
        "Chad", "Chile", "China", "Colombia", "Comoros", "Congo, Dem. Rep.",
        "Republic of the Congo", "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czech Republic",
        "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt",
        "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Swaziland", "Ethiopia",
        "Fiji", "Finland", "France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana",
        "Greece", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Honduras",
        "Hong Kong SAR, China", "Hungary", "Iceland", "India", "Indonesia",
        "Iran, Islamic Rep.", "Iraq", "Ireland", "Israel", "Italy", "Côte d'Ivoire",
        "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "South Korea",
        "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya",
        "Liechtenstein", "Lithuania", "Luxembourg", "Macao SAR, China", "Madagascar", "Malawi",
        "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania",
        "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro",
        "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Netherlands",
        "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Macedonia", "Norway", "Oman",
        "Pakistan", "Palau", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines",
        "Poland", "Portugal", "Qatar", "Romania", "Russian Federation", "Rwanda", "Samoa",
        "San Marino", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone",
        "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa",
        "South Sudan", "Spain", "Sri Lanka", "St. Kitts and Nevis", "St. Lucia",
        "St. Vincent and the Grenadines", "Sudan", "Suriname", "Sweden", "Switzerland",
        "Syrian Arab Republic", "Tajikistan", "Tanzania", "Thailand", "East Timor", "Togo",
        "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu",
        "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "Uruguay", "Uzbekistan",
        "Vanuatu", "Venezuela, RB", "Vietnam", "Yemen, Rep.", "Zambia", "Zimbabwe"],
        import: ["Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda",
        "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain",
        "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan",
        "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria",
        "Burkina Faso", "Burundi", "Cambodia", "Cameroon", "Canada", "Central African Republic",
        "Chad", "Chile", "China", "Colombia", "Comoros", "Congo, Dem. Rep.",
        "Republic of the Congo", "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czech Republic",
        "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt",
        "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Swaziland", "Ethiopia",
        "Fiji", "Finland", "France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana",
        "Greece", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Honduras",
        "Hong Kong SAR, China", "Hungary", "Iceland", "India", "Indonesia",
        "Iran, Islamic Rep.", "Iraq", "Ireland", "Israel", "Italy", "Côte d'Ivoire",
        "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "South Korea",
        "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya",
        "Liechtenstein", "Lithuania", "Luxembourg", "Macao SAR, China", "Madagascar", "Malawi",
        "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania",
        "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro",
        "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Netherlands",
        "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Macedonia", "Norway", "Oman",
        "Pakistan", "Palau", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines",
        "Poland", "Portugal", "Qatar", "Romania", "Russian Federation", "Rwanda", "Samoa",
        "San Marino", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone",
        "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa",
        "South Sudan", "Spain", "Sri Lanka", "St. Kitts and Nevis", "St. Lucia",
        "St. Vincent and the Grenadines", "Sudan", "Suriname", "Sweden", "Switzerland",
        "Syrian Arab Republic", "Tajikistan", "Tanzania", "Thailand", "East Timor", "Togo",
        "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu",
        "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "Uruguay", "Uzbekistan",
        "Vanuatu", "Venezuela, RB", "Vietnam", "Yemen, Rep.", "Zambia", "Zimbabwe"],
        top20: ["Category 2", "Category 4", "Category 6", "Category 7", "Category 8", "Category 9", "Category 20"]
    };

    // 이미지 경로 매핑
    const imageMapping = {
		gdp: {
			"Afghanistan": "../../assets/images/graphs/gdp/Afghanistan.png",
			"Albania": "../../assets/images/graphs/gdp/Albania.png",
			"Algeria": "../../assets/images/graphs/gdp/Algeria.png",
			"Andorra": "../../assets/images/graphs/gdp/Andorra.png",
			"Angola": "../../assets/images/graphs/gdp/Angola.png",
			"Antigua and Barbuda": "../../assets/images/graphs/gdp/Antigua and Barbuda.png",
			"Argentina": "../../assets/images/graphs/gdp/Argentina.png",
			"Armenia": "../../assets/images/graphs/gdp/Armenia.png",
			"Australia": "../../assets/images/graphs/gdp/Australia.png",
			"Austria": "../../assets/images/graphs/gdp/Austria.png",
			"Azerbaijan": "../../assets/images/graphs/gdp/Azerbaijan.png",
			"Bahamas": "../../assets/images/graphs/gdp/Bahamas.png",
			"Bahrain": "../../assets/images/graphs/gdp/Bahrain.png",
			"Bangladesh": "../../assets/images/graphs/gdp/Bangladesh.png",
			"Barbados": "../../assets/images/graphs/gdp/Barbados.png",
			"Belarus": "../../assets/images/graphs/gdp/Belarus.png",
			"Belgium": "../../assets/images/graphs/gdp/Belgium.png",
			"Belize": "../../assets/images/graphs/gdp/Belize.png",
			"Benin": "../../assets/images/graphs/gdp/Benin.png",
			"Bhutan": "../../assets/images/graphs/gdp/Bhutan.png",
			"Bolivia": "../../assets/images/graphs/gdp/Bolivia.png",
			"Bosnia and Herzegovina": "../../assets/images/graphs/gdp/Bosnia and Herzegovina.png",
			"Botswana": "../../assets/images/graphs/gdp/Botswana.png",
			"Brazil": "../../assets/images/graphs/gdp/Brazil.png",
			"Brunei": "../../assets/images/graphs/gdp/Brunei.png",
			"Bulgaria": "../../assets/images/graphs/gdp/Bulgaria.png",
			"Burkina Faso": "../../assets/images/graphs/gdp/Burkina Faso.png",
			"Burundi": "../../assets/images/graphs/gdp/Burundi.png",
			"Cambodia": "../../assets/images/graphs/gdp/Cambodia.png",
			"Cameroon": "../../assets/images/graphs/gdp/Cameroon.png",
			"Canada": "../../assets/images/graphs/gdp/Canada.png",
			"Central African Republic": "../../assets/images/graphs/gdp/Central African Republic.png",
			"Chad": "../../assets/images/graphs/gdp/Chad.png",
			"Chile": "../../assets/images/graphs/gdp/Chile.png",
			"China": "../../assets/images/graphs/gdp/China.png",
			"Colombia": "../../assets/images/graphs/gdp/Colombia.png",
			"Comoros": "../../assets/images/graphs/gdp/Comoros.png",
			"Congo, Dem. Rep.": "../../assets/images/graphs/gdp/Congo Dem Rep.png",
			"Republic of the Congo": "../../assets/images/graphs/gdp/Republic of the Congo.png",
			"Costa Rica": "../../assets/images/graphs/gdp/Costa Rica.png",
			"Croatia": "../../assets/images/graphs/gdp/Croatia.png",
			"Cuba": "../../assets/images/graphs/gdp/Cuba.png",
			"Cyprus": "../../assets/images/graphs/gdp/Cyprus.png",
			"Czech Republic": "../../assets/images/graphs/gdp/Czech Republic.png",
			"Denmark": "../../assets/images/graphs/gdp/Denmark.png",
			"Djibouti": "../../assets/images/graphs/gdp/Djibouti.png",
			"Dominica": "../../assets/images/graphs/gdp/Dominica.png",
			"Dominican Republic": "../../assets/images/graphs/gdp/Dominican Republic.png",
			"Ecuador": "../../assets/images/graphs/gdp/Ecuador.png",
			"Egypt": "../../assets/images/graphs/gdp/Egypt.png",
			"El Salvador": "../../assets/images/graphs/gdp/El Salvador.png",
			"Equatorial Guinea": "../../assets/images/graphs/gdp/Equatorial Guinea.png",
			"Eritrea": "../../assets/images/graphs/gdp/Eritrea.png",
			"Estonia": "../../assets/images/graphs/gdp/Estonia.png",
			"Swaziland": "../../assets/images/graphs/gdp/Swaziland.png",
			"Ethiopia": "../../assets/images/graphs/gdp/Ethiopia.png",
			"Fiji": "../../assets/images/graphs/gdp/Fiji.png",
			"Finland": "../../assets/images/graphs/gdp/Finland.png",
			"France": "../../assets/images/graphs/gdp/France.png",
			"Gabon": "../../assets/images/graphs/gdp/Gabon.png",
			"Gambia": "../../assets/images/graphs/gdp/Gambia.png",
			"Georgia": "../../assets/images/graphs/gdp/Georgia.png",
			"Germany": "../../assets/images/graphs/gdp/Germany.png",
			"Ghana": "../../assets/images/graphs/gdp/Ghana.png",
			"Greece": "../../assets/images/graphs/gdp/Greece.png",
			"Guatemala": "../../assets/images/graphs/gdp/Guatemala.png",
			"Guinea": "../../assets/images/graphs/gdp/Guinea.png",
			"Guinea-Bissau": "../../assets/images/graphs/gdp/Guinea Bissau.png",
			"Guyana": "../../assets/images/graphs/gdp/Guyana.png",
			"Haiti": "../../assets/images/graphs/gdp/Haiti.png",
			"Honduras": "../../assets/images/graphs/gdp/Honduras.png",
			"Hong Kong SAR, China": "../../assets/images/graphs/gdp/Hong Kong SAR China.png",
			"Hungary": "../../assets/images/graphs/gdp/Hungary.png",
			"Iceland": "../../assets/images/graphs/gdp/Iceland.png",
			"India": "../../assets/images/graphs/gdp/India.png",
			"Indonesia": "../../assets/images/graphs/gdp/Indonesia.png",
			"Iran, Islamic Rep.": "../../assets/images/graphs/gdp/Iran Islamic Rep.png",
			"Iraq": "../../assets/images/graphs/gdp/Iraq.png",
			"Ireland": "../../assets/images/graphs/gdp/Ireland.png",
			"Israel": "../../assets/images/graphs/gdp/Israel.png",
			"Italy": "../../assets/images/graphs/gdp/Italy.png",
			"Côte d'Ivoire": "../../assets/images/graphs/gdp/Cote d Ivoire.png",
			"Jamaica": "../../assets/images/graphs/gdp/Jamaica.png",
			"Japan": "../../assets/images/graphs/gdp/Japan.png",
			"Jordan": "../../assets/images/graphs/gdp/Jordan.png",
			"Kazakhstan": "../../assets/images/graphs/gdp/Kazakhstan.png",
			"Kenya": "../../assets/images/graphs/gdp/Kenya.png",
			"Kiribati": "../../assets/images/graphs/gdp/Kiribati.png",
			"South Korea": "../../assets/images/graphs/gdp/South Korea.png",
			"Kuwait": "../../assets/images/graphs/gdp/Kuwait.png",
			"Kyrgyzstan": "../../assets/images/graphs/gdp/Kyrgyzstan.png",
			"Laos": "../../assets/images/graphs/gdp/Laos.png",
			"Latvia": "../../assets/images/graphs/gdp/Latvia.png",
			"Lebanon": "../../assets/images/graphs/gdp/Lebanon.png",
			"Lesotho": "../../assets/images/graphs/gdp/Lesotho.png",
			"Liberia": "../../assets/images/graphs/gdp/Liberia.png",
			"Libya": "../../assets/images/graphs/gdp/Libya.png",
			"Liechtenstein": "../../assets/images/graphs/gdp/Liechtenstein.png",
			"Lithuania": "../../assets/images/graphs/gdp/Lithuania.png",
			"Luxembourg": "../../assets/images/graphs/gdp/Luxembourg.png",
			"Macao SAR, China": "../../assets/images/graphs/gdp/Macao SAR China.png",
			"Madagascar": "../../assets/images/graphs/gdp/Madagascar.png",
			"Malawi": "../../assets/images/graphs/gdp/Malawi.png",
			"Malaysia": "../../assets/images/graphs/gdp/Malaysia.png",
			"Maldives": "../../assets/images/graphs/gdp/Maldives.png",
			"Mali": "../../assets/images/graphs/gdp/Mali.png",
			"Malta": "../../assets/images/graphs/gdp/Malta.png",
			"Marshall Islands": "../../assets/images/graphs/gdp/Marshall Islands.png",
			"Mauritania": "../../assets/images/graphs/gdp/Mauritania.png",
			"Mauritius": "../../assets/images/graphs/gdp/Mauritius.png",
			"Mexico": "../../assets/images/graphs/gdp/Mexico.png",
			"Micronesia": "../../assets/images/graphs/gdp/Micronesia.png",
			"Moldova": "../../assets/images/graphs/gdp/Moldova.png",
			"Monaco": "../../assets/images/graphs/gdp/Monaco.png",
			"Mongolia": "../../assets/images/graphs/gdp/Mongolia.png",
			"Montenegro": "../../assets/images/graphs/gdp/Montenegro.png",
			"Morocco": "../../assets/images/graphs/gdp/Morocco.png",
			"Mozambique": "../../assets/images/graphs/gdp/Mozambique.png",
			"Myanmar": "../../assets/images/graphs/gdp/Myanmar.png",
			"Namibia": "../../assets/images/graphs/gdp/Namibia.png",
			"Nauru": "../../assets/images/graphs/gdp/Nauru.png",
			"Nepal": "../../assets/images/graphs/gdp/Nepal.png",
			"Netherlands": "../../assets/images/graphs/gdp/Netherlands.png",
			"New Zealand": "../../assets/images/graphs/gdp/New Zealand.png",
			"Nicaragua": "../../assets/images/graphs/gdp/Nicaragua.png",
			"Niger": "../../assets/images/graphs/gdp/Niger.png",
			"Nigeria": "../../assets/images/graphs/gdp/Nigeria.png",
			"North Macedonia": "../../assets/images/graphs/gdp/North Macedonia.png",
			"Norway": "../../assets/images/graphs/gdp/Norway.png",
			"Oman": "../../assets/images/graphs/gdp/Oman.png",
			"Pakistan": "../../assets/images/graphs/gdp/Pakistan.png",
			"Palau": "../../assets/images/graphs/gdp/Palau.png",
			"Panama": "../../assets/images/graphs/gdp/Panama.png",
			"Papua New Guinea": "../../assets/images/graphs/gdp/Papua New Guinea.png",
			"Paraguay": "../../assets/images/graphs/gdp/Paraguay.png",
			"Peru": "../../assets/images/graphs/gdp/Peru.png",
			"Philippines": "../../assets/images/graphs/gdp/Philippines.png",
			"Poland": "../../assets/images/graphs/gdp/Poland.png",
			"Portugal": "../../assets/images/graphs/gdp/Portugal.png",
			"Qatar": "../../assets/images/graphs/gdp/Qatar.png",
			"Romania": "../../assets/images/graphs/gdp/Romania.png",
			"Russian Federation": "../../assets/images/graphs/gdp/Russian Federation.png",
			"Rwanda": "../../assets/images/graphs/gdp/Rwanda.png",
			"Samoa": "../../assets/images/graphs/gdp/Samoa.png",
			"San Marino": "../../assets/images/graphs/gdp/San Marino.png",
			"Saudi Arabia": "../../assets/images/graphs/gdp/Saudi Arabia.png",
			"Senegal": "../../assets/images/graphs/gdp/Senegal.png",
			"Serbia": "../../assets/images/graphs/gdp/Serbia.png",
			"Seychelles": "../../assets/images/graphs/gdp/Seychelles.png",
			"Sierra Leone": "../../assets/images/graphs/gdp/Sierra Leone.png",
			"Singapore": "../../assets/images/graphs/gdp/Singapore.png",
			"Slovakia": "../../assets/images/graphs/gdp/Slovakia.png",
			"Slovenia": "../../assets/images/graphs/gdp/Slovenia.png",
			"Solomon Islands": "../../assets/images/graphs/gdp/Solomon Islands.png",
			"Somalia": "../../assets/images/graphs/gdp/Somalia.png",
			"South Africa": "../../assets/images/graphs/gdp/South Africa.png",
			"South Sudan": "../../assets/images/graphs/gdp/South Sudan.png",
			"Spain": "../../assets/images/graphs/gdp/Spain.png",
			"Sri Lanka": "../../assets/images/graphs/gdp/Sri Lanka.png",
			"St. Kitts and Nevis": "../../assets/images/graphs/gdp/St Kitts and Nevis.png",
			"St. Lucia": "../../assets/images/graphs/gdp/St Lucia.png",
			"St. Vincent and the Grenadines": "../../assets/images/graphs/gdp/St Vincent and the Grenadines.png",
			"Sudan": "../../assets/images/graphs/gdp/Sudan.png",
			"Suriname": "../../assets/images/graphs/gdp/Suriname.png",
			"Sweden": "../../assets/images/graphs/gdp/Sweden.png",
			"Switzerland": "../../assets/images/graphs/gdp/Switzerland.png",
			"Syrian Arab Republic": "../../assets/images/graphs/gdp/Syrian Arab Republic.png",
			"Tajikistan": "../../assets/images/graphs/gdp/Tajikistan.png",
			"Tanzania": "../../assets/images/graphs/gdp/Tanzania.png",
			"Thailand": "../../assets/images/graphs/gdp/Thailand.png",
			"East Timor": "../../assets/images/graphs/gdp/East Timor.png",
			"Togo": "../../assets/images/graphs/gdp/Togo.png",
			"Tonga": "../../assets/images/graphs/gdp/Tonga.png",
			"Trinidad and Tobago": "../../assets/images/graphs/gdp/Trinidad and Tobago.png",
			"Tunisia": "../../assets/images/graphs/gdp/Tunisia.png",
			"Turkey": "../../assets/images/graphs/gdp/Turkey.png",
			"Turkmenistan": "../../assets/images/graphs/gdp/Turkmenistan.png",
			"Tuvalu": "../../assets/images/graphs/gdp/Tuvalu.png",
			"Uganda": "../../assets/images/graphs/gdp/Uganda.png",
			"Ukraine": "../../assets/images/graphs/gdp/Ukraine.png",
			"United Arab Emirates": "../../assets/images/graphs/gdp/United Arab Emirates.png",
			"United Kingdom": "../../assets/images/graphs/gdp/United Kingdom.png",
			"United States": "../../assets/images/graphs/gdp/United States.png",
			"Uruguay": "../../assets/images/graphs/gdp/Uruguay.png",
			"Uzbekistan": "../../assets/images/graphs/gdp/Uzbekistan.png",
			"Vanuatu": "../../assets/images/graphs/gdp/Vanuatu.png",
			"Venezuela, RB": "../../assets/images/graphs/gdp/Venezuela RB.png",
			"Vietnam": "../../assets/images/graphs/gdp/Vietnam.png",
			"Yemen, Rep.": "../../assets/images/graphs/gdp/Yemen Rep.png",
			"Zambia": "../../assets/images/graphs/gdp/Zambia.png",
			"Zimbabwe": "../../assets/images/graphs/gdp/Zimbabwe.png"
		},
        governance: {
			"Afghanistan": "../../assets/images/graphs/governance/Afghanistan.png",
			"Albania": "../../assets/images/graphs/governance/Albania.png",
			"Algeria": "../../assets/images/graphs/governance/Algeria.png",
			"Andorra": "../../assets/images/graphs/governance/Andorra.png",
			"Angola": "../../assets/images/graphs/governance/Angola.png",
			"Antigua and Barbuda": "../../assets/images/graphs/governance/Antigua and Barbuda.png",
			"Argentina": "../../assets/images/graphs/governance/Argentina.png",
			"Armenia": "../../assets/images/graphs/governance/Armenia.png",
			"Australia": "../../assets/images/graphs/governance/Australia.png",
			"Austria": "../../assets/images/graphs/governance/Austria.png",
			"Azerbaijan": "../../assets/images/graphs/governance/Azerbaijan.png",
			"Bahamas": "../../assets/images/graphs/governance/Bahamas.png",
			"Bahrain": "../../assets/images/graphs/governance/Bahrain.png",
			"Bangladesh": "../../assets/images/graphs/governance/Bangladesh.png",
			"Barbados": "../../assets/images/graphs/governance/Barbados.png",
			"Belarus": "../../assets/images/graphs/governance/Belarus.png",
			"Belgium": "../../assets/images/graphs/governance/Belgium.png",
			"Belize": "../../assets/images/graphs/governance/Belize.png",
			"Benin": "../../assets/images/graphs/governance/Benin.png",
			"Bhutan": "../../assets/images/graphs/governance/Bhutan.png",
			"Bolivia": "../../assets/images/graphs/governance/Bolivia.png",
			"Bosnia and Herzegovina": "../../assets/images/graphs/governance/Bosnia and Herzegovina.png",
			"Botswana": "../../assets/images/graphs/governance/Botswana.png",
			"Brazil": "../../assets/images/graphs/governance/Brazil.png",
			"Brunei": "../../assets/images/graphs/governance/Brunei.png",
			"Bulgaria": "../../assets/images/graphs/governance/Bulgaria.png",
			"Burkina Faso": "../../assets/images/graphs/governance/Burkina Faso.png",
			"Burundi": "../../assets/images/graphs/governance/Burundi.png",
			"Cambodia": "../../assets/images/graphs/governance/Cambodia.png",
			"Cameroon": "../../assets/images/graphs/governance/Cameroon.png",
			"Canada": "../../assets/images/graphs/governance/Canada.png",
			"Central African Republic": "../../assets/images/graphs/governance/Central African Republic.png",
			"Chad": "../../assets/images/graphs/governance/Chad.png",
			"Chile": "../../assets/images/graphs/governance/Chile.png",
			"China": "../../assets/images/graphs/governance/China.png",
			"Colombia": "../../assets/images/graphs/governance/Colombia.png",
			"Comoros": "../../assets/images/graphs/governance/Comoros.png",
			"Congo, Dem. Rep.": "../../assets/images/graphs/governance/Congo Dem Rep.png",
			"Republic of the Congo": "../../assets/images/graphs/governance/Republic of the Congo.png",
			"Costa Rica": "../../assets/images/graphs/governance/Costa Rica.png",
			"Croatia": "../../assets/images/graphs/governance/Croatia.png",
			"Cuba": "../../assets/images/graphs/governance/Cuba.png",
			"Cyprus": "../../assets/images/graphs/governance/Cyprus.png",
			"Czech Republic": "../../assets/images/graphs/governance/Czech Republic.png",
			"Denmark": "../../assets/images/graphs/governance/Denmark.png",
			"Djibouti": "../../assets/images/graphs/governance/Djibouti.png",
			"Dominica": "../../assets/images/graphs/governance/Dominica.png",
			"Dominican Republic": "../../assets/images/graphs/governance/Dominican Republic.png",
			"Ecuador": "../../assets/images/graphs/governance/Ecuador.png",
			"Egypt": "../../assets/images/graphs/governance/Egypt.png",
			"El Salvador": "../../assets/images/graphs/governance/El Salvador.png",
			"Equatorial Guinea": "../../assets/images/graphs/governance/Equatorial Guinea.png",
			"Eritrea": "../../assets/images/graphs/governance/Eritrea.png",
			"Estonia": "../../assets/images/graphs/governance/Estonia.png",
			"Swaziland": "../../assets/images/graphs/governance/Swaziland.png",
			"Ethiopia": "../../assets/images/graphs/governance/Ethiopia.png",
			"Fiji": "../../assets/images/graphs/governance/Fiji.png",
			"Finland": "../../assets/images/graphs/governance/Finland.png",
			"France": "../../assets/images/graphs/governance/France.png",
			"Gabon": "../../assets/images/graphs/governance/Gabon.png",
			"Gambia": "../../assets/images/graphs/governance/Gambia.png",
			"Georgia": "../../assets/images/graphs/governance/Georgia.png",
			"Germany": "../../assets/images/graphs/governance/Germany.png",
			"Ghana": "../../assets/images/graphs/governance/Ghana.png",
			"Greece": "../../assets/images/graphs/governance/Greece.png",
			"Guatemala": "../../assets/images/graphs/governance/Guatemala.png",
			"Guinea": "../../assets/images/graphs/governance/Guinea.png",
			"Guinea-Bissau": "../../assets/images/graphs/governance/Guinea Bissau.png",
			"Guyana": "../../assets/images/graphs/governance/Guyana.png",
			"Haiti": "../../assets/images/graphs/governance/Haiti.png",
			"Honduras": "../../assets/images/graphs/governance/Honduras.png",
			"Hong Kong SAR, China": "../../assets/images/graphs/governance/Hong Kong SAR China.png",
			"Hungary": "../../assets/images/graphs/governance/Hungary.png",
			"Iceland": "../../assets/images/graphs/governance/Iceland.png",
			"India": "../../assets/images/graphs/governance/India.png",
			"Indonesia": "../../assets/images/graphs/governance/Indonesia.png",
			"Iran, Islamic Rep.": "../../assets/images/graphs/governance/Iran Islamic Rep.png",
			"Iraq": "../../assets/images/graphs/governance/Iraq.png",
			"Ireland": "../../assets/images/graphs/governance/Ireland.png",
			"Israel": "../../assets/images/graphs/governance/Israel.png",
			"Italy": "../../assets/images/graphs/governance/Italy.png",
			"Côte d'Ivoire": "../../assets/images/graphs/governance/Cote d Ivoire.png",
			"Jamaica": "../../assets/images/graphs/governance/Jamaica.png",
			"Japan": "../../assets/images/graphs/governance/Japan.png",
			"Jordan": "../../assets/images/graphs/governance/Jordan.png",
			"Kazakhstan": "../../assets/images/graphs/governance/Kazakhstan.png",
			"Kenya": "../../assets/images/graphs/governance/Kenya.png",
			"Kiribati": "../../assets/images/graphs/governance/Kiribati.png",
			"South Korea": "../../assets/images/graphs/governance/South Korea.png",
			"Kuwait": "../../assets/images/graphs/governance/Kuwait.png",
			"Kyrgyzstan": "../../assets/images/graphs/governance/Kyrgyzstan.png",
			"Laos": "../../assets/images/graphs/governance/Laos.png",
			"Latvia": "../../assets/images/graphs/governance/Latvia.png",
			"Lebanon": "../../assets/images/graphs/governance/Lebanon.png",
			"Lesotho": "../../assets/images/graphs/governance/Lesotho.png",
			"Liberia": "../../assets/images/graphs/governance/Liberia.png",
			"Libya": "../../assets/images/graphs/governance/Libya.png",
			"Liechtenstein": "../../assets/images/graphs/governance/Liechtenstein.png",
			"Lithuania": "../../assets/images/graphs/governance/Lithuania.png",
			"Luxembourg": "../../assets/images/graphs/governance/Luxembourg.png",
			"Macao SAR, China": "../../assets/images/graphs/governance/Macao SAR China.png",
			"Madagascar": "../../assets/images/graphs/governance/Madagascar.png",
			"Malawi": "../../assets/images/graphs/governance/Malawi.png",
			"Malaysia": "../../assets/images/graphs/governance/Malaysia.png",
			"Maldives": "../../assets/images/graphs/governance/Maldives.png",
			"Mali": "../../assets/images/graphs/governance/Mali.png",
			"Malta": "../../assets/images/graphs/governance/Malta.png",
			"Marshall Islands": "../../assets/images/graphs/governance/Marshall Islands.png",
			"Mauritania": "../../assets/images/graphs/governance/Mauritania.png",
			"Mauritius": "../../assets/images/graphs/governance/Mauritius.png",
			"Mexico": "../../assets/images/graphs/governance/Mexico.png",
			"Micronesia": "../../assets/images/graphs/governance/Micronesia.png",
			"Moldova": "../../assets/images/graphs/governance/Moldova.png",
			"Monaco": "../../assets/images/graphs/governance/Monaco.png",
			"Mongolia": "../../assets/images/graphs/governance/Mongolia.png",
			"Montenegro": "../../assets/images/graphs/governance/Montenegro.png",
			"Morocco": "../../assets/images/graphs/governance/Morocco.png",
			"Mozambique": "../../assets/images/graphs/governance/Mozambique.png",
			"Myanmar": "../../assets/images/graphs/governance/Myanmar.png",
			"Namibia": "../../assets/images/graphs/governance/Namibia.png",
			"Nauru": "../../assets/images/graphs/governance/Nauru.png",
			"Nepal": "../../assets/images/graphs/governance/Nepal.png",
			"Netherlands": "../../assets/images/graphs/governance/Netherlands.png",
			"New Zealand": "../../assets/images/graphs/governance/New Zealand.png",
			"Nicaragua": "../../assets/images/graphs/governance/Nicaragua.png",
			"Niger": "../../assets/images/graphs/governance/Niger.png",
			"Nigeria": "../../assets/images/graphs/governance/Nigeria.png",
			"North Macedonia": "../../assets/images/graphs/governance/North Macedonia.png",
			"Norway": "../../assets/images/graphs/governance/Norway.png",
			"Oman": "../../assets/images/graphs/governance/Oman.png",
			"Pakistan": "../../assets/images/graphs/governance/Pakistan.png",
			"Palau": "../../assets/images/graphs/governance/Palau.png",
			"Panama": "../../assets/images/graphs/governance/Panama.png",
			"Papua New Guinea": "../../assets/images/graphs/governance/Papua New Guinea.png",
			"Paraguay": "../../assets/images/graphs/governance/Paraguay.png",
			"Peru": "../../assets/images/graphs/governance/Peru.png",
			"Philippines": "../../assets/images/graphs/governance/Philippines.png",
			"Poland": "../../assets/images/graphs/governance/Poland.png",
			"Portugal": "../../assets/images/graphs/governance/Portugal.png",
			"Qatar": "../../assets/images/graphs/governance/Qatar.png",
			"Romania": "../../assets/images/graphs/governance/Romania.png",
			"Russian Federation": "../../assets/images/graphs/governance/Russian Federation.png",
			"Rwanda": "../../assets/images/graphs/governance/Rwanda.png",
			"Samoa": "../../assets/images/graphs/governance/Samoa.png",
			"San Marino": "../../assets/images/graphs/governance/San Marino.png",
			"Saudi Arabia": "../../assets/images/graphs/governance/Saudi Arabia.png",
			"Senegal": "../../assets/images/graphs/governance/Senegal.png",
			"Serbia": "../../assets/images/graphs/governance/Serbia.png",
			"Seychelles": "../../assets/images/graphs/governance/Seychelles.png",
			"Sierra Leone": "../../assets/images/graphs/governance/Sierra Leone.png",
			"Singapore": "../../assets/images/graphs/governance/Singapore.png",
			"Slovakia": "../../assets/images/graphs/governance/Slovakia.png",
			"Slovenia": "../../assets/images/graphs/governance/Slovenia.png",
			"Solomon Islands": "../../assets/images/graphs/governance/Solomon Islands.png",
			"Somalia": "../../assets/images/graphs/governance/Somalia.png",
			"South Africa": "../../assets/images/graphs/governance/South Africa.png",
			"South Sudan": "../../assets/images/graphs/governance/South Sudan.png",
			"Spain": "../../assets/images/graphs/governance/Spain.png",
			"Sri Lanka": "../../assets/images/graphs/governance/Sri Lanka.png",
			"St. Kitts and Nevis": "../../assets/images/graphs/governance/St Kitts and Nevis.png",
			"St. Lucia": "../../assets/images/graphs/governance/St Lucia.png",
			"St. Vincent and the Grenadines": "../../assets/images/graphs/governance/St Vincent and the Grenadines.png",
			"Sudan": "../../assets/images/graphs/governance/Sudan.png",
			"Suriname": "../../assets/images/graphs/governance/Suriname.png",
			"Sweden": "../../assets/images/graphs/governance/Sweden.png",
			"Switzerland": "../../assets/images/graphs/governance/Switzerland.png",
			"Syrian Arab Republic": "../../assets/images/graphs/governance/Syrian Arab Republic.png",
			"Tajikistan": "../../assets/images/graphs/governance/Tajikistan.png",
			"Tanzania": "../../assets/images/graphs/governance/Tanzania.png",
			"Thailand": "../../assets/images/graphs/governance/Thailand.png",
			"East Timor": "../../assets/images/graphs/governance/East Timor.png",
			"Togo": "../../assets/images/graphs/governance/Togo.png",
			"Tonga": "../../assets/images/graphs/governance/Tonga.png",
			"Trinidad and Tobago": "../../assets/images/graphs/governance/Trinidad and Tobago.png",
			"Tunisia": "../../assets/images/graphs/governance/Tunisia.png",
			"Turkey": "../../assets/images/graphs/governance/Turkey.png",
			"Turkmenistan": "../../assets/images/graphs/governance/Turkmenistan.png",
			"Tuvalu": "../../assets/images/graphs/governance/Tuvalu.png",
			"Uganda": "../../assets/images/graphs/governance/Uganda.png",
			"Ukraine": "../../assets/images/graphs/governance/Ukraine.png",
			"United Arab Emirates": "../../assets/images/graphs/governance/United Arab Emirates.png",
			"United Kingdom": "../../assets/images/graphs/governance/United Kingdom.png",
			"United States": "../../assets/images/graphs/governance/United States.png",
			"Uruguay": "../../assets/images/graphs/governance/Uruguay.png",
			"Uzbekistan": "../../assets/images/graphs/governance/Uzbekistan.png",
			"Vanuatu": "../../assets/images/graphs/governance/Vanuatu.png",
			"Venezuela, RB": "../../assets/images/graphs/governance/Venezuela RB.png",
			"Vietnam": "../../assets/images/graphs/governance/Vietnam.png",
			"Yemen, Rep.": "../../assets/images/graphs/governance/Yemen Rep.png",
			"Zambia": "../../assets/images/graphs/governance/Zambia.png",
			"Zimbabwe": "../../assets/images/graphs/governance/Zimbabwe.png"
		},
        import: {
			"Afghanistan": "../../assets/images/graphs/imports/Afghanistan.png",
			"Albania": "../../assets/images/graphs/imports/Albania.png",
			"Algeria": "../../assets/images/graphs/imports/Algeria.png",
			"Andorra": "../../assets/images/graphs/imports/Andorra.png",
			"Angola": "../../assets/images/graphs/imports/Angola.png",
			"Antigua and Barbuda": "../../assets/images/graphs/imports/Antigua_and_Barbuda.png",
			"Argentina": "../../assets/images/graphs/imports/Argentina.png",
			"Armenia": "../../assets/images/graphs/imports/Armenia.png",
			"Australia": "../../assets/images/graphs/imports/Australia.png",
			"Austria": "../../assets/images/graphs/imports/Austria.png",
			"Azerbaijan": "../../assets/images/graphs/imports/Azerbaijan.png",
			"Bahamas": "../../assets/images/graphs/imports/Bahamas.png",
			"Bahrain": "../../assets/images/graphs/imports/Bahrain.png",
			"Bangladesh": "../../assets/images/graphs/imports/Bangladesh.png",
			"Barbados": "../../assets/images/graphs/imports/Barbados.png",
			"Belarus": "../../assets/images/graphs/imports/Belarus.png",
			"Belgium": "../../assets/images/graphs/imports/Belgium.png",
			"Belize": "../../assets/images/graphs/imports/Belize.png",
			"Benin": "../../assets/images/graphs/imports/Benin.png",
			"Bhutan": "../../assets/images/graphs/imports/Bhutan.png",
			"Bolivia": "../../assets/images/graphs/imports/Bolivia.png",
			"Bosnia and Herzegovina": "../../assets/images/graphs/imports/Bosnia_and_Herzegovina.png",
			"Botswana": "../../assets/images/graphs/imports/Botswana.png",
			"Brazil": "../../assets/images/graphs/imports/Brazil.png",
			"Brunei": "../../assets/images/graphs/imports/Brunei.png",
			"Bulgaria": "../../assets/images/graphs/imports/Bulgaria.png",
			"Burkina Faso": "../../assets/images/graphs/imports/Burkina_Faso.png",
			"Burundi": "../../assets/images/graphs/imports/Burundi.png",
			"Cambodia": "../../assets/images/graphs/imports/Cambodia.png",
			"Cameroon": "../../assets/images/graphs/imports/Cameroon.png",
			"Canada": "../../assets/images/graphs/imports/Canada.png",
			"Central African Republic": "../../assets/images/graphs/imports/Central_African_Republic.png",
			"Chad": "../../assets/images/graphs/imports/Chad.png",
			"Chile": "../../assets/images/graphs/imports/Chile.png",
			"China": "../../assets/images/graphs/imports/China.png",
			"Colombia": "../../assets/images/graphs/imports/Colombia.png",
			"Comoros": "../../assets/images/graphs/imports/Comoros.png",
			"Congo, Dem. Rep.": "../../assets/images/graphs/imports/Congo_Dem_Rep.png",
			"Republic of the Congo": "../../assets/images/graphs/imports/Republic_of_the_Congo.png",
			"Costa Rica": "../../assets/images/graphs/imports/Costa_Rica.png",
			"Croatia": "../../assets/images/graphs/imports/Croatia.png",
			"Cuba": "../../assets/images/graphs/imports/Cuba.png",
			"Cyprus": "../../assets/images/graphs/imports/Cyprus.png",
			"Czech Republic": "../../assets/images/graphs/imports/Czech_Republic.png",
			"Denmark": "../../assets/images/graphs/imports/Denmark.png",
			"Djibouti": "../../assets/images/graphs/imports/Djibouti.png",
			"Dominica": "../../assets/images/graphs/imports/Dominica.png",
			"Dominican Republic": "../../assets/images/graphs/imports/Dominican_Republic.png",
			"Ecuador": "../../assets/images/graphs/imports/Ecuador.png",
			"Egypt": "../../assets/images/graphs/imports/Egypt.png",
			"El Salvador": "../../assets/images/graphs/imports/El_Salvador.png",
			"Equatorial Guinea": "../../assets/images/graphs/imports/Equatorial_Guinea.png",
			"Eritrea": "../../assets/images/graphs/imports/Eritrea.png",
			"Estonia": "../../assets/images/graphs/imports/Estonia.png",
			"Swaziland": "../../assets/images/graphs/imports/Swaziland.png",
			"Ethiopia": "../../assets/images/graphs/imports/Ethiopia.png",
			"Fiji": "../../assets/images/graphs/imports/Fiji.png",
			"Finland": "../../assets/images/graphs/imports/Finland.png",
			"France": "../../assets/images/graphs/imports/France.png",
			"Gabon": "../../assets/images/graphs/imports/Gabon.png",
			"Gambia": "../../assets/images/graphs/imports/Gambia.png",
			"Georgia": "../../assets/images/graphs/imports/Georgia.png",
			"Germany": "../../assets/images/graphs/imports/Germany.png",
			"Ghana": "../../assets/images/graphs/imports/Ghana.png",
			"Greece": "../../assets/images/graphs/imports/Greece.png",
			"Guatemala": "../../assets/images/graphs/imports/Guatemala.png",
			"Guinea": "../../assets/images/graphs/imports/Guinea.png",
			"Guinea-Bissau": "../../assets/images/graphs/imports/Guinea_Bissau.png",
			"Guyana": "../../assets/images/graphs/imports/Guyana.png",
			"Haiti": "../../assets/images/graphs/imports/Haiti.png",
			"Honduras": "../../assets/images/graphs/imports/Honduras.png",
			"Hong Kong SAR, China": "../../assets/images/graphs/imports/Hong_Kong_SAR_China.png",
			"Hungary": "../../assets/images/graphs/imports/Hungary.png",
			"Iceland": "../../assets/images/graphs/imports/Iceland.png",
			"India": "../../assets/images/graphs/imports/India.png",
			"Indonesia": "../../assets/images/graphs/imports/Indonesia.png",
			"Iran, Islamic Rep.": "../../assets/images/graphs/imports/Iran_Islamic_Rep.png",
			"Iraq": "../../assets/images/graphs/imports/Iraq.png",
			"Ireland": "../../assets/images/graphs/imports/Ireland.png",
			"Israel": "../../assets/images/graphs/imports/Israel.png",
			"Italy": "../../assets/images/graphs/imports/Italy.png",
			"Côte d'Ivoire": "../../assets/images/graphs/imports/Cote_d_Ivoire.png",
			"Jamaica": "../../assets/images/graphs/imports/Jamaica.png",
			"Japan": "../../assets/images/graphs/imports/Japan.png",
			"Jordan": "../../assets/images/graphs/imports/Jordan.png",
			"Kazakhstan": "../../assets/images/graphs/imports/Kazakhstan.png",
			"Kenya": "../../assets/images/graphs/imports/Kenya.png",
			"Kiribati": "../../assets/images/graphs/imports/Kiribati.png",
			"South Korea": "../../assets/images/graphs/imports/South_Korea.png",
			"Kuwait": "../../assets/images/graphs/imports/Kuwait.png",
			"Kyrgyzstan": "../../assets/images/graphs/imports/Kyrgyzstan.png",
			"Laos": "../../assets/images/graphs/imports/Laos.png",
			"Latvia": "../../assets/images/graphs/imports/Latvia.png",
			"Lebanon": "../../assets/images/graphs/imports/Lebanon.png",
			"Lesotho": "../../assets/images/graphs/imports/Lesotho.png",
			"Liberia": "../../assets/images/graphs/imports/Liberia.png",
			"Libya": "../../assets/images/graphs/imports/Libya.png",
			"Liechtenstein": "../../assets/images/graphs/imports/Liechtenstein.png",
			"Lithuania": "../../assets/images/graphs/imports/Lithuania.png",
			"Luxembourg": "../../assets/images/graphs/imports/Luxembourg.png",
			"Macao SAR, China": "../../assets/images/graphs/imports/Macao_SAR_China.png",
			"Madagascar": "../../assets/images/graphs/imports/Madagascar.png",
			"Malawi": "../../assets/images/graphs/imports/Malawi.png",
			"Malaysia": "../../assets/images/graphs/imports/Malaysia.png",
			"Maldives": "../../assets/images/graphs/imports/Maldives.png",
			"Mali": "../../assets/images/graphs/imports/Mali.png",
			"Malta": "../../assets/images/graphs/imports/Malta.png",
			"Marshall Islands": "../../assets/images/graphs/imports/Marshall_Islands.png",
			"Mauritania": "../../assets/images/graphs/imports/Mauritania.png",
			"Mauritius": "../../assets/images/graphs/imports/Mauritius.png",
			"Mexico": "../../assets/images/graphs/imports/Mexico.png",
			"Micronesia": "../../assets/images/graphs/imports/Micronesia.png",
			"Moldova": "../../assets/images/graphs/imports/Moldova.png",
			"Monaco": "../../assets/images/graphs/imports/Monaco.png",
			"Mongolia": "../../assets/images/graphs/imports/Mongolia.png",
			"Montenegro": "../../assets/images/graphs/imports/Montenegro.png",
			"Morocco": "../../assets/images/graphs/imports/Morocco.png",
			"Mozambique": "../../assets/images/graphs/imports/Mozambique.png",
			"Myanmar": "../../assets/images/graphs/imports/Myanmar.png",
			"Namibia": "../../assets/images/graphs/imports/Namibia.png",
			"Nauru": "../../assets/images/graphs/imports/Nauru.png",
			"Nepal": "../../assets/images/graphs/imports/Nepal.png",
			"Netherlands": "../../assets/images/graphs/imports/Netherlands.png",
			"New Zealand": "../../assets/images/graphs/imports/New_Zealand.png",
			"Nicaragua": "../../assets/images/graphs/imports/Nicaragua.png",
			"Niger": "../../assets/images/graphs/imports/Niger.png",
			"Nigeria": "../../assets/images/graphs/imports/Nigeria.png",
			"North Macedonia": "../../assets/images/graphs/imports/North_Macedonia.png",
			"Norway": "../../assets/images/graphs/imports/Norway.png",
			"Oman": "../../assets/images/graphs/imports/Oman.png",
			"Pakistan": "../../assets/images/graphs/imports/Pakistan.png",
			"Palau": "../../assets/images/graphs/imports/Palau.png",
			"Panama": "../../assets/images/graphs/imports/Panama.png",
			"Papua New Guinea": "../../assets/images/graphs/imports/Papua_New_Guinea.png",
			"Paraguay": "../../assets/images/graphs/imports/Paraguay.png",
			"Peru": "../../assets/images/graphs/imports/Peru.png",
			"Philippines": "../../assets/images/graphs/imports/Philippines.png",
			"Poland": "../../assets/images/graphs/imports/Poland.png",
			"Portugal": "../../assets/images/graphs/imports/Portugal.png",
			"Qatar": "../../assets/images/graphs/imports/Qatar.png",
			"Romania": "../../assets/images/graphs/imports/Romania.png",
			"Russian Federation": "../../assets/images/graphs/imports/Russian_Federation.png",
			"Rwanda": "../../assets/images/graphs/imports/Rwanda.png",
			"Samoa": "../../assets/images/graphs/imports/Samoa.png",
			"San Marino": "../../assets/images/graphs/imports/San_Marino.png",
			"Saudi Arabia": "../../assets/images/graphs/imports/Saudi_Arabia.png",
			"Senegal": "../../assets/images/graphs/imports/Senegal.png",
			"Serbia": "../../assets/images/graphs/imports/Serbia.png",
			"Seychelles": "../../assets/images/graphs/imports/Seychelles.png",
			"Sierra Leone": "../../assets/images/graphs/imports/Sierra_Leone.png",
			"Singapore": "../../assets/images/graphs/imports/Singapore.png",
			"Slovakia": "../../assets/images/graphs/imports/Slovakia.png",
			"Slovenia": "../../assets/images/graphs/imports/Slovenia.png",
			"Solomon Islands": "../../assets/images/graphs/imports/Solomon_Islands.png",
			"Somalia": "../../assets/images/graphs/imports/Somalia.png",
			"South Africa": "../../assets/images/graphs/imports/South_Africa.png",
			"South Sudan": "../../assets/images/graphs/imports/South_Sudan.png",
			"Spain": "../../assets/images/graphs/imports/Spain.png",
			"Sri Lanka": "../../assets/images/graphs/imports/Sri_Lanka.png",
			"St. Kitts and Nevis": "../../assets/images/graphs/imports/St_Kitts_and_Nevis.png",
			"St. Lucia": "../../assets/images/graphs/imports/St_Lucia.png",
			"St. Vincent and the Grenadines": "../../assets/images/graphs/imports/St_Vincent_and_the_Grenadines.png",
			"Sudan": "../../assets/images/graphs/imports/Sudan.png",
			"Suriname": "../../assets/images/graphs/imports/Suriname.png",
			"Sweden": "../../assets/images/graphs/imports/Sweden.png",
			"Switzerland": "../../assets/images/graphs/imports/Switzerland.png",
			"Syrian Arab Republic": "../../assets/images/graphs/imports/Syrian_Arab_Republic.png",
			"Tajikistan": "../../assets/images/graphs/imports/Tajikistan.png",
			"Tanzania": "../../assets/images/graphs/imports/Tanzania.png",
			"Thailand": "../../assets/images/graphs/imports/Thailand.png",
			"East Timor": "../../assets/images/graphs/imports/East_Timor.png",
			"Togo": "../../assets/images/graphs/imports/Togo.png",
			"Tonga": "../../assets/images/graphs/imports/Tonga.png",
			"Trinidad and Tobago": "../../assets/images/graphs/imports/Trinidad_and_Tobago.png",
			"Tunisia": "../../assets/images/graphs/imports/Tunisia.png",
			"Turkey": "../../assets/images/graphs/imports/Turkey.png",
			"Turkmenistan": "../../assets/images/graphs/imports/Turkmenistan.png",
			"Tuvalu": "../../assets/images/graphs/imports/Tuvalu.png",
			"Uganda": "../../assets/images/graphs/imports/Uganda.png",
			"Ukraine": "../../assets/images/graphs/imports/Ukraine.png",
			"United Arab Emirates": "../../assets/images/graphs/imports/United_Arab_Emirates.png",
			"United Kingdom": "../../assets/images/graphs/imports/United_Kingdom.png",
			"United States": "../../assets/images/graphs/imports/United_States.png",
			"Uruguay": "../../assets/images/graphs/imports/Uruguay.png",
			"Uzbekistan": "../../assets/images/graphs/imports/Uzbekistan.png",
			"Vanuatu": "../../assets/images/graphs/imports/Vanuatu.png",
			"Venezuela, RB": "../../assets/images/graphs/imports/Venezuela_RB.png",
			"Vietnam": "../../assets/images/graphs/imports/Vietnam.png",
			"Yemen, Rep.": "../../assets/images/graphs/imports/Yemen_Rep.png",
			"Zambia": "../../assets/images/graphs/imports/Zambia.png",
			"Zimbabwe": "../../assets/images/graphs/imports/Zimbabwe.png"
		},
        top20: {
			"Category 2": "../../assets/images/graphs/top20/Top 20 Arms Importing Countries by Category 2.png",
			"Category 4": "../../assets/images/graphs/top20/Top 20 Arms Importing Countries by Category 4.png",
			"Category 6": "../../assets/images/graphs/top20/Top 20 Arms Importing Countries by Category 6.png",
			"Category 7": "../../assets/images/graphs/top20/Top 20 Arms Importing Countries by Category 7.png",
			"Category 8": "../../assets/images/graphs/top20/Top 20 Arms Importing Countries by Category 8.png",
			"Category 9": "../../assets/images/graphs/top20/Top 20 Arms Importing Countries by Category 9.png",
			"Category 20": "../../assets/images/graphs/top20/Top 20 Arms Importing Countries by Category 20.png"
		}		
    };

    function resetToDefault() {
        countrySelector.innerHTML = '<option value="" selected disabled>Country/Category</option>';
        imageContainer.innerHTML = '<p>Please select a chart type and country/category.</p>';
    }

    chartTypeSelector.addEventListener('change', () => {
        const selectedChart = chartTypeSelector.value;
        resetToDefault();
        if (chartData[selectedChart]) {
            chartData[selectedChart].forEach(item => {
                const option = document.createElement('option');
                option.value = item;
                option.textContent = item;
                countrySelector.appendChild(option);
            });
        }
    });

    countrySelector.addEventListener('change', () => {
        const selectedChart = chartTypeSelector.value;
        const selectedCategory = countrySelector.value;
        if (imageMapping[selectedChart] && imageMapping[selectedChart][selectedCategory]) {
            const imagePath = imageMapping[selectedChart][selectedCategory];
            imageContainer.innerHTML = `<img src="${imagePath}" alt="${selectedCategory}" style="max-width: 100%; height: auto; border: 1px solid #ddd; border-radius: 5px;">`;
        } else {
            imageContainer.innerHTML = '<p style="color: red;">No image available for this category.</p>';
        }
    });
});